language: node_js
node_js: stable
branches:
  only:
  - source
cache:
  directories:
  - node_modules
before_install:
- npm install -g hexo
- npm install -g hexo-cli
- npm install hexo-deployer-git --save
- npm install -S hexo-generator-json-content
before_script:
- git config --global user.name 'wisimer'
- git config --global user.email 'wisimer@163.com'
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
env:
  global:
    secure: LIMJhsb5Z4zZxyvUS/D7idZnMYYrsFTGLzm5ECG9CKY9iOg/ru7BML+6M0nyBb45e0bxOVGiwI4lVDzoMQ4KAeZ8HVNyElgqH05KptZW/ST4WGxgOofxq0nhqhlZ3pL8QRJ+Zf2WTkXgAzX3BLGvDpgDsgFBxPbPxjco5np21aJ1O0EjeGiZ3NqpamJG4cy8WRDNadFkTBIb/xpF7kY0I7Yhaatlbw7KFh2oKOqAqBZZyUhwlf4AMJcWIvgpLzVLtrNkfWmHrkV2J+QvEcFTBPifAPw1dJ31qBfjZQNmqE1BTXIy7i6KDetUCesb5pIe1asGEo/UIBjgxfqfSS5VHkW8X9hvDb2I+hrFhQvLzOrN8Huh7TlXPytJACROtOa0fD7zalHDrZ2cV+Xgl3Oj19BNWHJAYdMWktMTW8krdbmo1TAQIa30nUIs8tEnSQeyFchFcphumKzRjKMigcWKTq5CCXRlRzdJwW3s+yrdO3uPLIrI4tDnAjXKiaD1HSNJ9RbfDbGzIVYBHxIckBKIBpRNtxxw8iju0qxZUMS4cnpPZihZlc2Wg+vwjrOHS36UaAvxhU/NxOceBOmMj6UQdejUFHpIChp9AhUgsQSOfFSQEnL/Et5/4Zv3FjYE5YpzomkpoQL4GkjkOAB42XBXKHSlXKOJJf9O3YjfshScYDQ=
