language: node_js
node_js: stable
# assign build branches
branches:
  only:
    - source
# cache this directory
cache:
  directories:
    - node_modules
# S: Build Lifecycle
before_install:
  - openssl aes-256-cbc -K $encrypted_d76e2cf77261_key -iv $encrypted_d76e2cf77261_iv -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - git config --global user.name "wisimer"
  - git config --global user.email "wisimer@163.com"
  - npm install -g hexo-cli
install:
  - npm install
  - npm install hexo-deployer-git --save
script:
  - hexo clean
  - hexo generate
after_script:
  - git config user.name "wisimer"
  - git config user.email "wisimer@163.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
